name: train_tracker
description: "Train-Tracker"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: 4.19.2
  firebase_core: ^2.30.0
  flutter_dotenv: ^5.1.0
  email_validator: ^2.0.1
  image_picker: ^1.0.7
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
