// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1YW6-BP6XaHpCPI87ccGefyGCBamsjNg',
    appId: '1:1005616374074:web:f912b727aff8304423b003',
    messagingSenderId: '1005616374074',
    projectId: 'api-project-1005616374074',
    authDomain: 'api-project-1005616374074.firebaseapp.com',
    storageBucket: 'api-project-1005616374074.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzE6_o2Kzkj5Vx0wSJLXZ0uUBIBJkcf4',
    appId: '1:1005616374074:android:114b610cda39adfd23b003',
    messagingSenderId: '1005616374074',
    projectId: 'api-project-1005616374074',
    storageBucket: 'api-project-1005616374074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjqm6pVjPETMMjkIXi8ltZIHJCo_6EDM',
    appId: '1:1005616374074:ios:eb8de57dbb9f21d123b003',
    messagingSenderId: '1005616374074',
    projectId: 'api-project-1005616374074',
    storageBucket: 'api-project-1005616374074.appspot.com',
    iosBundleId: 'com.example.trainTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjqm6pVjPETMMjkIXi8ltZIHJCo_6EDM',
    appId: '1:1005616374074:ios:eb8de57dbb9f21d123b003',
    messagingSenderId: '1005616374074',
    projectId: 'api-project-1005616374074',
    storageBucket: 'api-project-1005616374074.appspot.com',
    iosBundleId: 'com.example.trainTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1YW6-BP6XaHpCPI87ccGefyGCBamsjNg',
    appId: '1:1005616374074:web:de736f2ffa39be5823b003',
    messagingSenderId: '1005616374074',
    projectId: 'api-project-1005616374074',
    authDomain: 'api-project-1005616374074.firebaseapp.com',
    storageBucket: 'api-project-1005616374074.appspot.com',
  );
}
